import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Link from "next/link";
import Sidebar from "@/components/sidebar/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ChakraProvider>
      <div className="flex">
        <Sidebar />
        <div className="w-full">
          <div className=" w-full">{children}</div>
        </div>
      </div>
    </ChakraProvider>
  );
}
